### ISSUE TITLE
mock grpc without packageName

### ISSUE THREAD

**Issue by PrinsWu** [YoshiyukiKato/grpc-kit#6]
Hi,

When I test grpc with mocha and grpc-mock, it's find if I use the proto.greeter.Greeter.Hello example.
But I got error when I without packageName parameter, because the proto file that I use that does not have it. (And I have no permission to change it)

Is there any possible use it without packageName?

`
TypeError: Cannot read property 'split' of undefined
    at getProtoFromPackageDefinition (/Users/prinswu/client/beanfun/projects/backend_business/server/node_modules/grpc-kit/index.js:5:31)
    at GrpcServer.use (/Users/prinswu/client/beanfun/projects/backend_business/server/node_modules/grpc-kit/index.js:26:19)
    at createMockServer (/Users/prinswu/client/beanfun/projects/backend_business/server/node_modules/grpc-mock/index.js:22:21)
`

Thanks!

**Comment by zupay** [comment]
This is easily fixed by testing for empty string here:

function getProtoFromPackageDefinition(packageDefinition, packageName) { 
 const pathArr = packageName.split(".");
  return pathArr.reduce((obj, key) => (obj && obj[key] !== 'undefined') ? obj[key] : undefined, packageDefinition);
}
